### ISSUE TITLE
utils is no longer a class

### ISSUE THREAD

**Issue by Hacksore** [Hacksore/skinpreview3d.js#5]
No longer need the "utils" prefix as `convertSkinTo1_8` is a global method within the skinpreview3d namespace.

https://github.com/Hacksore/skinpreview3d.js/blob/71583ec3b5c2fd1e94544118632919bfb265e29e/js/skinpreview3d.js#L423

**Comment by yushijinhun** [comment]
Nice catch! It was my mistake. I will solve this tomorrow.

**Comment by Hacksore** [comment]
No problem, you're doing awesome work!

Also with this issue, there does not need to be a _this_ call on `copyImage` as it is a global method.
https://github.com/Hacksore/skinpreview3d.js/blob/master/js/skinpreview3d.js#L45
