### ISSUE TITLE
Native javascript invocation to take object

### ISSUE THREAD

**Issue by Hacksore** [Hacksore/skinpreview3d.js#9]
Might be a good idea to allow for the native JS invocation to have an object argument rather than several passed in.

So instead of this
```javascript
var skinViewer = new skinpreview3d.SkinViewer(document.getElementById('skin_container'), 600, 600, true);
```

It could be refactored to something like this.
```javascript
var skinViewer = new skinpreview3d.SkinViewer({
	domElement: document.getElementById('skin_container'),
	skinUrl: 'img/hatsune_miku.png',
	capeUrl: 'img/mojang_cape.png',
	slim: false,
	width: 600,
	height: 600
});
```
This will help for documentation as well as streamlining the two configurations for jQuery and native javascript.

**Comment by yushijinhun** [comment]
I agree with you. Also, I'd like to make width, height and model type(default or slim) modificable at runtime.

I want to add some other new features, such as the elytra support and customizable motions. It may take some time to implement them.

Sorry for the late reply. I'm busy these days because of the new semester.

**Comment by Hacksore** [comment]
This is not something that is needed ASAP just a nice consistency feature.

When you are speaking of elytra do you mean this [https://minecraft.gamepedia.com/Elytra](https://minecraft.gamepedia.com/Elytra). I've been out of the Minecraft update loop for some time now but would that mean you'd like to implement the basic armor models as well?

Lastly, when you referred to height/width/model type at run time do you mean something like attributes in the HTML?

`<div id="model" data-skin-url="/some/path" data-skin-type="slim"></div>`
